spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1/twtr
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    org:
      springframework:
        jdbc: debug
    clone:
      twitter:
        repository: trace

mybatis:
  type-aliases-package: clone.twitter.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
