spring:
  profiles:
    active: local
  datasource:
    primary-mysql:
      url: jdbc:mysql://127.0.0.1/twitterlocal-primary
      username: root
      password:
    replica-mysql:
      url: jdbc:mysql://127.0.0.1/twitterlocal-replica
      username: root
      password:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  session:
    store-type: redis
  redis:
    session:
      host:
      port:
      password:
    fan-out:
      host:
      port:
      password:
    cluster:
      nodes:
        - host1:port
        - host2:port
        - host3:port
        - host4:port
        - host5:port
        - host6:port

logging:
  level:
    org:
      springframework:
        jdbc: debug
    clone:
      twitter:
        repository: trace

# # MyBatisConfig.sqlSessionFactory에서 정의하는 것으로 변경
#mybatis:
#  type-aliases-package: clone.twitter.domain
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/**/*.xml
